version: 2
jobs:
  build:
    # must be IROHA_HOME:
    working_directory: /opt/iroha
    docker:
      - image: lebdron/iroha-dev
        environment:
          IROHA_HOME: /opt/iroha
          IROHA_BUILD: /tmp/build
    steps:
      - checkout

      - run:
          name: ensure, required folders created
          command: |
            mkdir -p $IROHA_HOME
            mkdir -p $IROHA_BUILD
      - run:
          name: cmake
          command: |
            cd $IROHA_BUILD
            cmake $IROHA_HOME
      - run:
          name: make
          command: |
            cd $IROHA_BUILD
            make -j2
      - run:
          name: run tests
          command: |
            export TEST_FOLDER=$IROHA_BUILD/test_bin
            total=0
            for file in ${TEST_FOLDER}/*; do
                # run test
                ${file}
                total=$((total + $?)) 
            done
            exit $total

 